### ISSUE TITLE
Doesn't open on POP OS when i hover over or click

### ISSUE THREAD

**Issue by DurgNomis-drol** [mrvnklm/homeassistant-desktop#24]
Great app

But on Pop OS it doesn't open when i hover over or left click on it, it instead opens the settings menu when i left click/right click. Hover does nothing.

Shortcut (Ctrl + alt + X) doesn't work either.

**Comment by Fliwatt** [comment]
Same on 

Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-65-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

it used to work too, which is a shame because I loved this app.

**Comment by mrvnklm** [comment]
Do you guys have that issue just recently after the last update?

**Comment by DurgNomis-drol** [comment]
Yes, i have only used the latest version.

**Comment by Fliwatt** [comment]
Hey, thanks for the answer. Interestingly enough this seems to have come from an OS update since I do not remember upgrading the app and rolling back to 1.3.2 did not fix it.

**Comment by Wouter0100** [comment]
Doesn't work either on Ubuntu 20.10.

**Comment by mrvnklm** [comment]
I updated all dependencies, please check if it is working with the new release.

**Comment by mrvnklm** [comment]
Fixed, closing.
