### ISSUE TITLE
Error when resetted

### ISSUE THREAD

**Issue by qaqak** [mrvnklm/homeassistant-desktop#28]
Every time I reset the app to add a different instance link, I get a JavaScript error:
```
Uncaught Exception:
ReferenceError: window is not defined
  at Tray.<anonymous>
(C:\Users\*****\AppData\Local\Programs\homeassistant-desktop\resources\app.asar\a...:7)
  at Tray.emit (events.js:210:5)
```
I have to keep reinstalling the app :(
How do I fix this

**Comment by chertvl** [comment]
Same! Win10 Home

**Comment by qaqak** [comment]
I wanted to create my own Home Assistant Electron app.
Also, I'm surprised that someone commented after it was release a few months ago

**Comment by ThomasRitter75** [comment]
In 1.4.2 I get this error on every start and then the menu has only one entry, the configured instance. No config, no reset

**Comment by mrvnklm** [comment]
Can you try same as explained here https://github.com/mrvnklm/homeassistant-desktop/issues/57#issuecomment-962410915

**Comment by ThomasRitter75** [comment]
@mrvnklm Sorry, I didn't say, because the error was the same: I am on Ubuntu Linux. (AppImage). I killed the app (without menu this only works via task manager / kill) and removed ~/.config/homeassistant/ completely, then tried 1.4.3 and 1.4.4. Both give me

```
(node:3405279) UnhandledPromiseRejectionWarning: ReferenceError: tray is not defined
    at changePosition (/tmp/.mount_Home-AO1kXRq/resources/app.asar/app.js:98:22)
    at showWindow (/tmp/.mount_Home-AO1kXRq/resources/app.asar/app.js:468:35)
    at createMainWindow (/tmp/.mount_Home-AO1kXRq/resources/app.asar/app.js:462:13)
    at async App.<anonymous> (/tmp/.mount_Home-AO1kXRq/resources/app.asar/app.js:555:3)
(Use `homeassistant-desktop --trace-warnings ...` to show where the warning was created)
(node:3405279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3405279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

1.4.3 and 1.4.4 both will not show up in the tray at all, 1.4.3 will spawn background processes, but 1.4.4 will not start anything at all.

Then I removed the config directory again, redownloaded 1.4.0, because I knew that worked (The automatic update always deletes the file when everything is removed) and 1.4.0 worked, but auto-upgraded to 1.4.4. And now, 1.4.4 works as it should, without error.

**Comment by mrvnklm** [comment]
Should be fixed, closing.
