### ISSUE TITLE
Unable to configure instance

### ISSUE THREAD

**Issue by Hobbit44** [mrvnklm/homeassistant-desktop#56]
I input the url or ip and port into the dialog and i cant confirm the input. I dont get any feedback on whether anything is wrong.

![image](https://user-images.githubusercontent.com/21823930/137128679-a19b770b-fc6b-4ada-a5b3-648f25f0523d.png)

OS: Windows 11 Pro Version 10.0.22000 Build 22000
App version: 1.4.0

**Comment by mrvnklm** [comment]
I updated all dependencies, please check if it is working with the new release.

**Comment by mrvnklm** [comment]
If there is a Home Assistant instance running on the provided address (including port), it will automatically forward to the login screen.

**Comment by ccmattr** [comment]
So I can get it to work, but I would highly recommend adding a confirmation button rather than auto recognition. You don't get any feedback on whats wrong. If i just enter an ip and port its not recognized and i cant tell why. when i tried adding the http prefix and i got as far as `http:` before it got accepted and i had to reset it to enter the full url with the http prefix.
![image](https://user-images.githubusercontent.com/83646278/141457572-40f0b823-86ad-4526-bdcd-e3123b92584b.png)

**Comment by mrvnklm** [comment]
> So I can get it to work, but I would highly recommend adding a confirmation button rather than auto recognition. You don't get any feedback on whats wrong. If i just enter an ip and port its not recognized and i cant tell why. when i tried adding the http prefix and i got as far as `http:` before it got accepted and i had to reset it to enter the full url with the http prefix. ![image](https://user-images.githubusercontent.com/83646278/141457572-40f0b823-86ad-4526-bdcd-e3123b92584b.png)

Yes, I noticed that as well. Will be fixed in the future.
